spring:
  application:
    name: memorybox_cert

#swagger
springdoc:
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /swagger.html
    enabled: true
    operationsSorter: alpha
    disable-swagger-default-url: true
    display-request-duration: true    #try it out ?? ? request duration ? ??? ???
    doc-expansion : none    # api?? ?? ???
  #    groups-order: DESC
  api-docs:
    enabled: true
    path: /api-docs