kind: Deployment
apiVersion: apps/v1
metadata:
  name: memorybox-cert
  labels:
    app: memorybox-cert
spec:
  selector:
    matchLabels:
      app: memorybox-cert
  replicas: 1
  template:
    metadata:
      name: memorybox-cert
      labels:
        app: memorybox-cert
    spec:
      imagePullSecrets:
      - name: dockerhub
      containers:
        - name: memorybox-cert
          image: docker.io/hyeonkyo/memorybox-cert:1.0.0
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "8080"
          envFrom:
            - configMapRef:
                name: memorybox-cm
            - secretRef:
                name: memorybox-secret
          ports:
            - name: port1
              containerPort: 8081
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1024Mi

---

apiVersion: v1
kind: Service
metadata:
  name: memorybox-cert
spec:
  type: ClusterIP
  selector:
    app: memorybox-cert
  ports:
    - name: memorybox-cert
      port: 8080
      targetPort: 8080